services:
  - type: web
    name: tech-memo-quiz
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 2 -k gthread -b 0.0.0.0:$PORT memorization_study:app
    autoDeploy: true
